@startuml
title SSD - Opret Gæstebesøg (Opret Gæstebesøg)
skinparam style strictuml

actor Medarbejder
participant ":System" as System

loop for hver gæst
  Medarbejder -> System : Opret Besøg (navn, firma, ank/afg tidspunkt, dato, ansvarlig)
  System --> Medarbejder : Besøg tilføjet
end
@enduml

