@startuml
title HYDAC Designklassediagram

hide circle
hide empty members

skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 80

skinparam class {
    BackgroundColor white
    BorderColor #555555
}

class Program {
    ~ Main(args : string[]) : void
}

class Menu <<static>> {
    + erLoggetind : bool
    + aktivMedarbejder : string = ""
    --
    + MenuShow() : void
}

class Medarbejder {
    - brugernavn : string
    - kode : string
    + Brugernavn : string
    + Kode : string
    + MedarbejderListe : List<Medarbejder>
    --
    + Medarbejder(brugernavn : string, kode : string)
    + OpretMedarbejder() : void
    + ListeMedarbejder() : void
    + Login() : void
    + LogOut() : void
}

class Besøg {
    + Navn : string
    + Firma : string
    + Ansvarlig : string
    + ForventetAnkomst : DateTime
    + ForventetAfgang : DateTime
    + IndTjekTid : DateTime?
    + UdTjekTid : DateTime?
    + Lokale : string
    + IndtjekningsKode : int
    + Status : string
    + Sikkerhedsfolder : bool
    + Date : DateTime?
    + BesøgListe : List<Besøg>
    --
    + Besøg(navn : string, firma : string, ansvarlig : string,
        forventetAnkomst : DateTime, forventetAfgang : DateTime,
        date : DateTime?, indtjektid : DateTime?, udtjektid : DateTime?,
        lokale : string, indtjekningsKode : int, status : string,
        sikkerhedsfolder : bool)
    + AddBesøg() : void
    + ListeBesøg() : void
    + TjekInd(sikkerhedsfolder : bool) : void
    + TjekUd() : void
    + FindBesøg(indtjekningskode : int) : Besøg?
    + TjekGæstInd() : void
    + TjekGæstUd() : void
}
Program -- Menu 
Menu -- Besøg 
Menu -- Medarbejder


@enduml
