@startuml
title HYDAC Designklassediagram

hide circle
hide empty members

skinparam classAttributeIconSize 0
skinparam pageMargin 40
left to right direction
skinparam nodesep 40
skinparam ranksep 100

skinparam rectangle {
    BackgroundColor white
    BorderColor #FFFFFF
}

skinparam class {
    BackgroundColor white
    BorderColor #555555
}

rectangle " " as bakgrund {

class Program <<internal>> {
    - {static} Main(args : string[]) : void
}


class Menu {
    + {static} erLoggetInd : bool
    + {static} aktivMedarbejder : string = ""
    --
    + {static} MenuShow() : void
}


class Medarbejder {
    - brugernavn : string
    - kode : string
    + Brugernavn : string
    + Kode : string
    + {static} medarbejderliste : List<Medarbejder>
    --
    + Medarbejder(brugernavn : string, kode : string)
    + {static} OpretMedarbejder() : void
    + {static} VisMedarbejderliste() : void
    + {static} LogInd() : void
    + {static} LogUd() : void
}


class Besøg {
    + GæstNavn : string
    + Firma : string
    + Ansvarlig : string
    + Lokale : string
    + Dato : DateTime?
    + ForventetAnkomsttid : DateTime
    + ForventetAfgangstid : DateTime
    + Indtjekningstid : DateTime?
    + Udtjekningstid : DateTime?
    + Indtjekningskode : int
    + Status : string
    + SikkerhedsfolderModtaget : bool
    + {static} gæsteliste : List<Besøg>
    --
    + Besøg(
        gæstNavn : string,
        firma : string,
        ansvarlig : string,
        forventetAnkomsttid : DateTime,
        forventetAfgangstid : DateTime,
        dato : DateTime?,
        indtjekningstid : DateTime?,
        udtjekningstid : DateTime?,
        lokale : string,
        indtjekningskode : int,
        status : string,
        sikkerhedsfolderModtaget : bool
    )
    - {static} LæsDato(i : string) : DateTime
    + {static} OpretBesøg() : void
    + {static} VisGæsteliste() : void
    + {static} FindBesøg(indtjekningskode : int) : Besøg?
    + {static} TjekInd() : void
    + {static} TjekGæstUd() : void
    + TjekInd(sikkerhedsfolderModtaget : bool) : void
    + TjekUd() : void
}

Program "1" -- "1" Menu : starter
Menu "1" -- "0..*" Besøg : besøgsListe
Menu "1  " - "1..*  " Medarbejder :   medarbejdere
Medarbejder "1" -- "1" Besøg : ansvarlige
}

@enduml
