@startuml
skinparam style strictuml
title UC03 - Medarbejderliste

actor Medarbejder
participant ":System" as System

  Medarbejder -> System : Vis Medarbejderliste (navn)
  System --> Medarbejder : Medarbejderliste vises

@enduml

