@startuml
skinparam style strictuml
title UC04 - Gæsteliste

actor Medarbejder
participant ":System" as System

  Medarbejder -> System : Vis Gæsteliste (navn, firma, ank/afg tidspunkt, dato, ansvarlig)
  System --> Medarbejder : Gæsteliste vises

@enduml

