@startuml
skinparam style strictuml
title UC05 - Tjek Gæst Ind
actor "Medarbejder" as Medarbejder
participant ":System" as System

System --> Medarbejder : System spørger om indtjekningskode
Medarbejder -> System : Indsætter Indtjekningskode
System --> Medarbejder : Sikkerhedsfolder modtaget ja/nej
Medarbejder -> System : Giver svar på modtagelse.
System --> Medarbejder : Status ændres til Tjekket Ind
@enduml
