@startuml
skinparam style strictuml
title UC06 - Tjek Gæst ind

actor Medarbejder
participant ":System" as System

System --> Medarbejder : System spørger om Indtjekningskode
Medarbejder -> System : Indsætter Indtjekningskode
System --> Medarbejder : Status ændres til Tjekket Ud
@enduml
