@startuml
skinparam style strictuml
title SSD - Opret Gæstebesøg (Opret Medarbejder)

actor Medarbejder
participant ":System" as System

Medarbejder -> System : Opret Medarbejder(Navn, Kode)
System --> Medarbejder : Medarbejder oprettet
@enduml

