@startuml
skinparam style strictuml
skinparam ParticipantBackgroundColor white
skinparam NoteBackgroundColor white
skinparam SequenceLifeLineBackgroundColor white
skinparam SequenceGroupBackgroundColor white
title SD: UC02 Opret Besøg

participant "Besøg" as BK
participant "rnd : Random" as R
participant "b : Besøg" as B
participant "BesøgListe : List<Besøg>" as L

[-> BK : AddBesøg()
activate BK

opt Menu.erLoggetind == true
    note over BK
        navn, firma, date, forventetankomst,
        forventetafgang, lokale og ansvarlig
        indlæses fra UI-laget (Console)
    end note

    create R
    BK -> R : create()
    BK -> R : indtjekningskode = Next(10_000_000, 100_000_000)

    rnote over BK
        indtjektid = Convert.ToDateTime(null)
        udtjektid = Convert.ToDateTime(null)
        status = "Ikke Tjekket Ind"
        sikkerhedsfolder = false
    end rnote


    create B
    BK -> B : create(...)
    note right of BK
        create(navn, firma, ansvarlig, forventetankomst,
        forventetafgang, date, indtjektid, udtjektid, lokale,
        indtjekningskode, status, sikkerhedsfolder)
    end note
    BK -> L : Add(b)
end
[<-- BK
deactivate BK
@enduml
