@startuml
skinparam style strictuml
title SD: Registrer besøg
participant ":System" as S
participant ":Besøg" as B
participant ":Gæst" as G

create B
S -> B : create(medarbejderID)
S<-- B : besøgsID

S-> B : tilføjGæst(navn, firma)
create G
B -> G : create(navn, firma)

B --> S : tidspunkt
@enduml