@startuml Hydac_Domaenemodel_v2

skinparam backgroundColor White
skinparam shadowing false
skinparam defaultFontName Arial
skinparam roundCorner 8
skinparam linetype polyline
skinparam nodesep 110
skinparam ranksep 70
skinparam padding 3
skinparam titleFontStyle bold

hide circle
hide methods

skinparam class {
    BackgroundColor White
    BorderColor #BBBBBB
    ArrowColor #444444
    FontColor Black
    AttributeFontColor Black
}

title Hydac Objektmodel

class "m1: Medarbejder" as Medarbejder {
    brugernavn = "Lars Hansen"
    kode = "LH1234"
}

class "b1: Besøg" as Besog {
    dato = "30/09/2026"
    forventet ankomst tid = "12:00"
    forventet afgangs tid = "16:00"
    lokale = "X01"
    status = "Tjekket Ind"
    indtjekningskode = "81507192"
}

class "g1: Gæst" as Gaest {
    navn = "Søren Mortensen"
    firma = "Bilka"
}

class "i1: Indtjekning" as Indtjekning {
    indtjeknings tid = "12:05"
    sikkerhedsfolder modtagelse = "Ja"
}

class "u1: Udtjekning" as Udtjekning {
    udtjeknings tid = " "
}



Medarbejder "1" -right- "0..*" Besog : ansvarlig for
Besog "1" -right- "1" Gaest : omfatter

Besog "1" -- "0..1" Indtjekning : registreres ved
Besog "1" -- "0..1" Udtjekning : afsluttes ved

Indtjekning -[hidden]right- Udtjekning

@enduml
