@startuml
title HYDAC Designklassediagram

hide circle
hide empty members

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80

skinparam class {
    BackgroundColor white
    BorderColor #555555
}

class Menu {
    - ErloggetInd : bool
    - medarbejdere : List<Medarbejder>
    - besøgsListe : List<Besøg>
    --
     + __VisMenu() : void__
    - Login() : void
    - __OpretMedarbejder() : void__
    - __OpretBesøg() : void__
    - __VisMedarbejderListe() : void__
    - __VisGæsteListe() : void__
    - __TjekInd() : void__
    - __TjekUd() : void__
}


class Medarbejder {
    + Brugernavn : string
    - Kode : string
    --
    + Medarbejder(Brugernavn : string, kode : string)
    + TjekKode(kode : string) : bool
}


class Besøg {
    + Gæst : string
    + Firma : string
    + Ansvarlig : Medarbejder
    + Lokale : string
    + Dato : DateTime
    + ForventetAnkomst : DateTime
    + ForventetAfgang : DateTime
    + tjekketIndTidspunkt : DateTime?
    + tjekketUdTidspunkt : DateTime?
    + Indtjekningskode : int
    + Status : string
    + SikkerhedsfolderModtaget : bool
    --
    + Besøg(
        Navn : Gæst,
        ansvarlig : Medarbejder,
        dato : DateTime,
        forventetAnkomst : DateTime,
        forventetAfgang : DateTime
    )
    + TjekInd(sikkerhedsfolderModtaget : bool) : void
    + TjekUd() : void
  }

Menu "1" -- "1..*" Medarbejder : medarbejdere
Menu "1" -- "0..*" Besøg : besøgsListe

Besøg "1" -- "1" Medarbejder : ansvarlig




@enduml