@startuml
title Hydac Designklassediagram

hide circle
hide empty members
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam class {
  BackgroundColor white
  BorderColor #555555
  }

class Menu {
  - loggetInd : bool
  - medarbejdere : List<Medarbejder>
  - besøgsListe : List<Besøg>
  --
  + VisMenu() : void
  - Login() : void
  - OpretMedarbejder() : void
  - OpretBesøg() : void
  - VisMedarbejderListe() : void
  - VisGæsteListe() : void
  - TjekIndUd() : void
}

class Medarbejder {
  - brugernavn : string
  - kode : string
  --
  + Medarbejder(brugernavn : string, kode : string)
  + TjekKode(kode : string) : bool
}

class Gæst {
  - navn : string
  - firma : string
  --
  + Gæst(navn : string, firma : string)
  + GetNavn() : string
}

class Besøg {
  + Gæst : Gæst
  + Firma : Firma
  + Ansvarlig : Medarbejder
  + ForventetAnkomst : DateTime
  + ForventetAfgang : DateTime
  + Lokale : string
  + Indtjekningskode : int
  + Status : bool
  + SikkerhedsfolderModtaget : bool
  --
  + Besøg(gæst : Gæst, ansvarlig : Medarbejder, forventetAnkomst : DateTime,\n forventetAfgang : DateTime, lokale : string)
  + TjekInd(sikkerhedsfolderModtaget : bool) : void
  + TjekUd() : void
  + GetIndtjekningskode() : int
  + GetStatus() : string
}

Menu "1" -- "1..*" Medarbejder : medarbejdere
Menu "1" -- "0..*" Besøg : besøgsListe

Besøg "0..*" -- "1" Medarbejder : ansvarlig
Besøg "0..*" -- "1" Gæst : gæst

@enduml
