@startuml
skinparam style strictuml
skinparam ParticipantBackgroundColor white
skinparam NoteBackgroundColor white
skinparam SequenceLifeLineBackgroundColor white
skinparam SequenceGroupBackgroundColor white
title SD: UC02 Opret besøg

participant "Menu" as M
participant "Besøg" as K
participant "gæsteliste : List<Besøg>" as L

[-> M : MenuShow()
activate M
note over M : svar = "2"

M -> K : OpretBesøg()
activate K

alt Menu.erLoggetInd
    note over K
        gæstNavn, firma, lokale og ansvarlig
        indlæses fra konsollen
    end note

    K -> K : dato = LæsDato("Indtast Dato: ")
    K -> K : forventetAnkomsttid = LæsDato("Indtast Forventet Ankomsttid: ")
    K -> K : forventetAfgangstid = LæsDato("Indtast Forventet Afgangstid: ")
    K -> K : indtjekningskode = Random.Next(10_000_000, 100_000_000)

    create participant "b : Besøg" as B
    K -> B : create(gæstNavn, firma, ansvarlig, forventetAnkomsttid,\nforventetAfgangstid, dato, indtjekningstid, udtjekningstid,\nlokale, indtjekningskode, status, sikkerhedsfolderModtaget)
    activate B
    rnote over B
        status = "Ikke Tjekket Ind"
        sikkerhedsfolderModtaget = false
        indtjekningstid = udtjekningstid = DateTime.MinValue
    end rnote
    deactivate B

    K -> L : Add(b)
else ikke logget ind
    note over K : "Du skal være logget ind!"
end

K --> M
deactivate K
deactivate M
@enduml
